#!/usr/bin/env bash

VERSION="3.1"
echo "Swift $VERSION Continuous Integration";

# Determine OS
UNAME=`uname`;
if [[ $UNAME == "Darwin" ]];
then
    OS="macos";
    OS_FILE="osx";
else
    if [[ $UNAME == "Linux" ]];
    then
        UBUNTU_RELEASE=`lsb_release -a 2>/dev/null`;
        if [[ $UBUNTU_RELEASE == *"16.10"* ]];
        then
            OS="ubuntu1610";
            OS_FILE="ubuntu16.10";
        elif [[ $UBUNTU_RELEASE == *"16.04"* ]];
        then
            OS="ubuntu1604";
            OS_FILE="ubuntu16.04";
        elif [[ $UBUNTU_RELEASE == *"14.04"* ]];
        then
            OS="ubuntu1404";
            OS_FILE="ubuntu14.04";
        else
            echo "Unsupported Operating System: $UBUNTU_RELEASE";
            exit 1; 
        fi
    else
        echo "Unsupported Operating System: $UNAME";
        exit 1; 
    fi
fi
echo "ğŸ–¥ Operating System: $OS";

if [[ $OS != "macos" ]];
then
    echo "ğŸ“š Installing Swift Dependencies"
    sudo apt-get install -y clang libicu-dev uuid-dev

    echo "ğŸ¦ Installing Swift";
    SWIFTFILE=swift-3.1-RELEASE-$OS_FILE
    wget https://swift.org/builds/swift-3.1-release/$OS/swift-3.1-RELEASE/$SWIFTFILE.tar.gz
    tar -zxf $SWIFTFILE.tar.gz
    export PATH=$PWD/$SWIFTFILE/usr/bin:"${PATH}"

    echo "ğŸ“¦  Installing Vapor Dependencies"
    sudo apt-get install -y openssl libmysqlclient-dev

else
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew install ctls
fi

echo "ğŸ“… Version: `swift --version`";

echo "ğŸš€ Building";
swift build
if [[ $? != 0 ]]; 
then 
    echo "âŒ  Build failed";
    exit 1; 
fi

echo "ğŸ’¼ Building Release";
swift build -c release
if [[ $? != 0 ]]; 
then 
    echo "âŒ  Build for release failed";
    exit 1; 
fi

echo "ğŸ” Testing";

swift test
if [[ $? != 0 ]]; 
then 
    echo "âŒ Tests failed";
    exit 1; 
fi

echo "âœ… Done"

